#!/usr/bin/env python3
"""Stage 4: orchestration characterizations."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
recs = json.load(open(os.path.join(DATA, "master_stage3.json")))
by = {r["paper_id"]: r for r in recs}

C = {}

C["O02"] = dict(
    in_orch=True, network_generation="5G", domain="Multi-domain (RAN/core/transport across operators)",
    orchestrator_type="D - orchestration architecture (multi-domain slicing with federated resource management)",
    architecture="Multi-domain network slicing orchestration architecture with a federation layer that brokers slice requests across administrative domains.",
    control_plane="3GPP management plane concepts; multi-domain slice manager plus federated resource broker (no single standard MANO implementation named)",
    managed_resources="Radio, transport and cloud resources contributed by each domain",
    input="Inter-domain slice requests with QoS/KPI requirements; per-domain resource availability",
    output="Federated slice instantiation and per-domain resource commitments",
    interfaces="Inter-domain slice/resource brokering interfaces (conceptual; not a named standard API)",
    centralized_or_distributed="Hierarchical: centralised federation layer over distributed domain managers",
    single_or_multidomain="Multi-domain",
    closed_loop="Partly - resource commitments are monitored; the orchestration loop itself is described architecturally rather than executed in a closed loop",
    sla_support="Yes (inter-domain SLA/KPI mapping)",
    network_slicing="Yes", cloud_native="NR", kubernetes="NR", oran="No",
    optimization="NR", ml="NR", agent="No", llm="No",
    evaluation_platform="NR (architectural paper)", network_scale="NR",
    baselines="NR", metrics="NR", main_results="NR",
    limitations="Architecture-level contribution: multi-domain federation is described but not experimentally validated end to end; no optimisation engine or learning component specified.",
    research_gap="Inter-domain slice orchestration lacks a concrete, evaluated optimisation engine and closed-loop assurance; a natural place to insert learning-based or LLM-based decision making.",
    source_url="https://doi.org/10.1109/MNET.2019.1800204", evidence="BIB",
)

C["O03"] = dict(
    in_orch=True, network_generation="5G", domain="End-to-end (RAN, transport, core)",
    orchestrator_type="G - survey/tutorial (not a primary experimental paper)",
    architecture="Survey of 5G network slicing using SDN and NFV: taxonomy, architectures and open challenges.",
    control_plane="ETSI NFV MANO, SDN controllers, 3GPP management (surveyed)",
    managed_resources="Surveyed", input="N/A", output="N/A", interfaces="Surveyed",
    centralized_or_distributed="Both surveyed", single_or_multidomain="Both surveyed",
    closed_loop="Surveyed", sla_support="Surveyed", network_slicing="Yes",
    cloud_native="Surveyed", kubernetes="Surveyed", oran="No",
    optimization="Surveyed", ml="Surveyed", agent="No", llm="No",
    evaluation_platform="N/A (survey)", network_scale="N/A", baselines="N/A", metrics="N/A",
    main_results="N/A (survey)",
    limitations="Survey - describes the landscape rather than contributing a new orchestrator; predates cloud-native and LLM-era orchestration.",
    research_gap="Provides the taxonomy against which newer AI-native orchestrators should be positioned.",
    source_url="https://doi.org/10.1016/j.comnet.2018.12.005", evidence="BIB", is_survey=True,
)

C["O04"] = dict(
    in_orch=True, network_generation="5G/6G", domain="End-to-end management and orchestration",
    orchestrator_type="F - LLM-based orchestrator (intent-centric management)",
    architecture="LLM-centric intent-based management framework: natural-language intents are translated by an LLM into management actions/policies for the network.",
    control_plane="Management plane (intent-driven management); mapped onto standard management functions",
    managed_resources="Network services and slices",
    input="Natural-language operator intents",
    output="Machine-readable intents / management actions",
    interfaces="NR (framework-level)", centralized_or_distributed="Centralised LLM-based intent engine",
    single_or_multidomain="NR", closed_loop="No (intent translation focus; assurance loop not demonstrated)",
    sla_support="Intent-level objectives", network_slicing="Yes (intents for slices)",
    cloud_native="NR", kubernetes="NR", oran="No",
    optimization="LLM prompting", ml="LLM", agent="No", llm="Yes (specific model NR)",
    evaluation_platform="NR", network_scale="NR", baselines="NR", metrics="NR",
    main_results="NR (magazine article describing the framework)",
    limitations="Magazine-level contribution: framework and architecture rather than a measured closed-loop deployment; no network-level KPI evaluation reported.",
    research_gap="Intent translation is demonstrated but intent assurance (does the network actually satisfy the intent?) and closed-loop correction remain open.",
    source_url="https://doi.org/10.1109/MNET.2024.3420120", evidence="BIB",
)

C["O05"] = dict(
    in_orch=True, network_generation="5G and beyond", domain="End-to-end (network and service management)",
    orchestrator_type="D - orchestration architecture / research agenda",
    architecture="AI-driven zero-touch network and service management (ZSM) architecture: closed-loop automation with AI/ML at multiple time scales.",
    control_plane="ETSI ZSM reference architecture (management plane); intent-driven",
    managed_resources="Network services, slices, VNFs, infrastructure",
    input="Telemetry, KPIs, intents", output="Management actions / policy changes",
    interfaces="ETSI ZSM service interfaces (conceptual)", centralized_or_distributed="Hierarchical and distributed control loops",
    single_or_multidomain="Both", closed_loop="Yes (conceptually - closed-loop automation is the core proposal)",
    sla_support="Yes", network_slicing="Yes", cloud_native="Yes (discussed)", kubernetes="Discussed", oran="No",
    optimization="ML/DRL proposed", ml="Yes", agent="No", llm="No",
    evaluation_platform="NR (agenda paper)", network_scale="NR", baselines="NR", metrics="NR", main_results="NR",
    limitations="Research-directions article: proposes the ZSM AI architecture and lists challenges without experimental validation; predates LLM-based agents.",
    research_gap="Defines the closed-loop ZSM target that later LLM/agent work must satisfy; the hard problems it lists (conflict resolution, assurance, multi-domain) are still open.",
    source_url="https://doi.org/10.1109/MNET.001.1900252", evidence="SUB",
)

C["O06"] = dict(
    in_orch=True, network_generation="6G", domain="Multi-domain / massive slice deployment",
    orchestrator_type="D - orchestration architecture",
    architecture="Zero-touch management and orchestration architecture for massive deployments of network slices in 6G, with AI-driven closed loops.",
    control_plane="ETSI ZSM / 3GPP management, cloud-native",
    managed_resources="Network slices at scale across domains",
    input="Slice descriptors, telemetry, KPIs", output="Slice lifecycle actions",
    interfaces="Conceptual", centralized_or_distributed="Hierarchical",
    single_or_multidomain="Multi-domain", closed_loop="Yes (conceptual)",
    sla_support="Yes", network_slicing="Yes", cloud_native="Yes", kubernetes="Discussed", oran="No",
    optimization="AI/ML", ml="Yes", agent="No", llm="No",
    evaluation_platform="NR", network_scale="NR", baselines="NR", metrics="NR", main_results="NR",
    limitations="Magazine-level architecture proposal without implementation or measurement.",
    research_gap="Scale and lifecycle automation of very large slice counts remains unvalidated; concrete decision engines are not specified.",
    source_url="https://doi.org/10.1109/MWC.009.00366", evidence="SUB",
)

C["O08"] = dict(
    in_orch=True, network_generation="5G", domain="Core / cloud-native",
    orchestrator_type="D - orchestration architecture (cloud-native)",
    architecture="Cloud-native approach to 5G network slicing: service-based architecture with containerised network functions and slice-specific orchestration.",
    control_plane="Cloud-native management and orchestration (container orchestration over NFV)",
    managed_resources="Containerised 5G network functions and slices",
    input="Slice requirements", output="Containerised slice deployments",
    interfaces="NR", centralized_or_distributed="Centralised orchestration over distributed infrastructure",
    single_or_multidomain="Single domain (per operator)", closed_loop="No",
    sla_support="Yes", network_slicing="Yes", cloud_native="Yes", kubernetes="Discussed (container orchestration)",
    oran="No", optimization="NR", ml="No", agent="No", llm="No",
    evaluation_platform="NR", network_scale="NR", baselines="NR", metrics="NR", main_results="NR",
    limitations="Magazine-level architecture; no experimental evaluation; predates modern Kubernetes-based 5G cores.",
    research_gap="The cloud-native substrate for slice orchestration is described but joint optimisation of container placement and network resources is not solved.",
    source_url="https://doi.org/10.1109/MCOM.2017.1600924", evidence="BIB", is_foundational=True,
)

C["O09"] = dict(
    in_orch=True, network_generation="Generic/NFV", domain="Core / cloud (NFV)",
    orchestrator_type="A - true orchestrator implementation (VNF orchestration with placement and chaining)",
    architecture="VNF orchestrator that places and chains virtual network functions over a distributed cloud, minimising end-to-end service latency.",
    control_plane="ETSI NFV MANO-style orchestrator",
    managed_resources="VNF instances, compute nodes, network links",
    input="Service requests (VNF chains) with latency budgets; node and link capacities; measured node/link delays",
    output="VNF placement and chaining decisions",
    interfaces="NR",
    centralized_or_distributed="Centralised orchestrator",
    single_or_multidomain="Single domain (distributed cloud)", closed_loop="Partly (placement based on measured delays; no continuous re-optimisation loop reported)",
    sla_support="Latency budgets", network_slicing="No (services rather than slices)",
    cloud_native="No (VM-era)", kubernetes="No", oran="No",
    optimization="Exact/heuristic optimisation of placement + chaining",
    ml="No", agent="No", llm="No",
    evaluation_platform="Simulation of a distributed cloud (exact platform NR)",
    network_scale="NR", baselines="NR", metrics="End-to-end latency, orchestration cost",
    main_results="The orchestrator reduces service latency versus latency-agnostic placement (exact figures not verified from the free record).",
    limitations="Static, one-shot placement optimisation; no learning, no closed-loop re-optimisation, no slice abstraction.",
    research_gap="Placement/ chaining optimisation is solved offline; online, learning-based and SLA-assured orchestration is not addressed - the gap later filled (partly) by DRL-based placement work.",
    source_url="https://doi.org/10.1109/TNSM.2016.2569020", evidence="SUB", is_foundational=True,
)

C["O10"] = dict(
    in_orch=True, network_generation="Generic/NFV", domain="Core / cloud (NFV)",
    orchestrator_type="G - survey/tutorial",
    architecture="Survey of virtual resource and VNF placement problems and solutions.",
    control_plane="NFV MANO (surveyed)", managed_resources="Surveyed",
    input="N/A", output="N/A", interfaces="Surveyed",
    centralized_or_distributed="Both surveyed", single_or_multidomain="Both surveyed",
    closed_loop="Surveyed", sla_support="Surveyed", network_slicing="Surveyed",
    cloud_native="Surveyed", kubernetes="No", oran="No",
    optimization="Surveyed (MILP, heuristics, metaheuristics)", ml="Surveyed", agent="No", llm="No",
    evaluation_platform="N/A (survey)", network_scale="N/A", baselines="N/A", metrics="N/A",
    main_results="N/A (survey)",
    limitations="Survey - consolidates placement formulations; does not itself provide an orchestration engine.",
    research_gap="The survey's own open-issues list (online, multi-objective, multi-domain placement) remains relevant and is only partly addressed by later DRL work.",
    source_url="https://doi.org/10.1109/COMST.2018.2884835", evidence="BIB", is_survey=True,
)

C["O16"] = dict(
    in_orch=True, network_generation="5G", domain="O-RAN",
    orchestrator_type="D - orchestration/architecture study with primary experimental evidence on xApp design",
    architecture="Open RAN xApp design and evaluation: how xApps are built, controlled and evaluated on programmable O-RAN platforms.",
    control_plane="O-RAN near-RT RIC (non-RT RIC/SMO for rApps)",
    managed_resources="Radio resources controlled through xApps",
    input="E2 telemetry (KPMs), xApp policies", output="E2 control actions",
    interfaces="E2, A1, O1", centralized_or_distributed="Hierarchical (SMO/non-RT above near-RT RIC)",
    single_or_multidomain="Single domain (RAN)", closed_loop="Yes (xApp control loops)",
    sla_support="Partly (KPI targets)", network_slicing="Yes (slice-aware xApps)",
    cloud_native="Yes", kubernetes="Yes (xApps as containers)", oran="Yes",
    optimization="xApp-specific", ml="Yes (ML-based xApps)", agent="No", llm="No",
    evaluation_platform="Open RAN programmable experimental platforms (e.g. Colosseum/OpenRAN Gym class platforms)",
    network_scale="NR", baselines="NR", metrics="KPI-level (per-xApp)", main_results="NR",
    limitations="Studies xApp design practice and challenges rather than proposing a single orchestrator; cross-xApp conflict resolution across many xApps remains open.",
    research_gap="xApp conflict mitigation and multi-xApp coordination in the RIC - the gap that later distillation/agent work targets.",
    source_url="https://doi.org/10.1109/JSAC.2023.3336186", evidence="BIB",
)

C["O22"] = dict(
    in_orch=True, network_generation="6G", domain="O-RAN",
    orchestrator_type="G - survey/tutorial",
    architecture="Tutorial and survey on explainable AI in 6G O-RAN: architecture, use cases, challenges.",
    control_plane="O-RAN SMO / RIC (surveyed)", managed_resources="Surveyed",
    input="N/A", output="N/A", interfaces="Surveyed (A1/E2/O1)",
    centralized_or_distributed="Surveyed", single_or_multidomain="Surveyed",
    closed_loop="Surveyed", sla_support="Surveyed", network_slicing="Surveyed",
    cloud_native="Surveyed", kubernetes="Surveyed", oran="Yes",
    optimization="Surveyed", ml="Surveyed", agent="No", llm="No",
    evaluation_platform="N/A (survey)", network_scale="N/A", baselines="N/A", metrics="N/A",
    main_results="N/A (survey)",
    limitations="Survey - provides the XAI vocabulary for O-RAN but no new orchestration mechanism.",
    research_gap="Explainability and trust requirements for AI-native O-RAN control are defined but rarely implemented in closed-loop orchestrators - highly relevant to LLM-agent adoption.",
    source_url="https://doi.org/10.1109/COMST.2024.3492168", evidence="BIB", is_survey=True,
)

C["O23"] = dict(
    in_orch=True, network_generation="5G to 6G", domain="End-to-end slicing / resource management",
    orchestrator_type="G - survey/tutorial",
    architecture="Survey of resource management from single-domain 5G to end-to-end 6G network slicing.",
    control_plane="Surveyed (3GPP, ETSI, O-RAN)", managed_resources="Surveyed",
    input="N/A", output="N/A", interfaces="Surveyed",
    centralized_or_distributed="Surveyed", single_or_multidomain="Both surveyed",
    closed_loop="Surveyed", sla_support="Surveyed", network_slicing="Yes",
    cloud_native="Surveyed", kubernetes="Surveyed", oran="Surveyed",
    optimization="Surveyed", ml="Surveyed (incl. DRL)", agent="No", llm="No",
    evaluation_platform="N/A (survey)", network_scale="N/A", baselines="N/A", metrics="N/A",
    main_results="N/A (survey)",
    limitations="Survey - documents that end-to-end multi-domain slicing resource management remains open.",
    research_gap="Directly states the multi-domain end-to-end resource-management gap that a cross-domain AI orchestrator would address.",
    source_url="https://doi.org/10.1109/COMST.2024.3350256", evidence="BIB", is_survey=True,
)

C["O24"] = dict(
    in_orch=True, network_generation="5G/6G", domain="Communication, network and service management",
    orchestrator_type="G - survey/tutorial (LLM for network/service management)",
    architecture="Survey of LLMs applied to communication, network and service management.",
    control_plane="Surveyed", managed_resources="Surveyed", input="N/A", output="N/A", interfaces="Surveyed",
    centralized_or_distributed="Surveyed", single_or_multidomain="Surveyed",
    closed_loop="Surveyed", sla_support="Surveyed", network_slicing="Surveyed",
    cloud_native="Surveyed", kubernetes="Surveyed", oran="Surveyed",
    optimization="Surveyed", ml="Surveyed", agent="Surveyed", llm="Yes",
    evaluation_platform="N/A (survey)", network_scale="N/A", baselines="N/A", metrics="N/A",
    main_results="N/A (survey)",
    limitations="Survey - the most current consolidated picture of LLM-based management; necessarily incomplete for 2026 work.",
    research_gap="Confirms that LLM-based management is mostly advisory and that closed-loop, SLA-scored LLM control is unproven.",
    source_url="https://doi.org/10.1109/COMST.2025.3548039", evidence="SUB", is_survey=True,
)

C["O27"] = dict(
    in_orch=True, network_generation="5G", domain="End-to-end slicing (orchestration)",
    orchestrator_type="B - optimisation/learning algorithm usable by an orchestrator",
    architecture="Multi-agent reinforcement learning architecture for network slice orchestration: agents manage slice resource allocation collaboratively.",
    control_plane="Management/orchestration layer (conceptual mapping)",
    managed_resources="Slice resources (compute/network)",
    input="Slice demand and state", output="Resource allocation per slice",
    interfaces="NR", centralized_or_distributed="Distributed multi-agent with coordination",
    single_or_multidomain="Single domain", closed_loop="Yes (RL feedback loop)",
    sla_support="Yes (slice requirements in reward)", network_slicing="Yes",
    cloud_native="NR", kubernetes="No", oran="No",
    optimization="MARL (multi-agent RL)", ml="Yes (MARL)", agent="Yes (RL agents)", llm="No",
    evaluation_platform="Simulation (platform NR)", network_scale="NR", baselines="NR",
    metrics="Slice-level resource/utility metrics", main_results="NR",
    limitations="Focuses on the learning algorithm for slice resource allocation; slice lifecycle management and MANO integration are out of scope, so it is an allocation engine rather than a full orchestrator.",
    research_gap="Multi-agent slice allocation exists, but coupling it to MANO lifecycle operations and to closed-loop SLA assurance is open.",
    source_url="https://doi.org/10.1109/MedComNet52149.2021.9501271", evidence="BIB",
)

C["O31"] = dict(
    in_orch=True, network_generation="5G and earlier", domain="End-to-end (multi-domain network services)",
    orchestrator_type="G - survey/tutorial",
    architecture="Survey of network service orchestration: concepts, enablers, projects and open challenges.",
    control_plane="ETSI NFV MANO, SDN, cloud orchestration (surveyed)",
    managed_resources="Surveyed", input="N/A", output="N/A", interfaces="Surveyed",
    centralized_or_distributed="Surveyed", single_or_multidomain="Both surveyed",
    closed_loop="Surveyed", sla_support="Surveyed", network_slicing="Surveyed",
    cloud_native="Surveyed", kubernetes="Surveyed", oran="No",
    optimization="Surveyed", ml="Surveyed", agent="No", llm="No",
    evaluation_platform="N/A (survey)", network_scale="N/A", baselines="N/A", metrics="N/A",
    main_results="N/A (survey)",
    limitations="Survey (2019) - predates the LLM/agent wave; useful as the baseline definition of 'orchestration'.",
    research_gap="Establishes the vocabulary that distinguishes orchestration from resource allocation, which later AI work often blurs.",
    source_url="https://doi.org/10.1016/j.comcom.2019.04.008", evidence="SUB", is_survey=True, is_foundational=True,
)

C["O32"] = dict(
    in_orch=True, network_generation="Generic", domain="End-to-end (knowledge plane)",
    orchestrator_type="D - orchestration architecture (knowledge plane)",
    architecture="Knowledge-Defined Networking: adds a knowledge plane (with ML and reasoning) above the data and control planes to automate network operation.",
    control_plane="Knowledge plane above SDN control plane",
    managed_resources="Network-wide resources", input="Network telemetry and state",
    output="Policies and control actions derived from learned knowledge",
    interfaces="Northbound interfaces to the control plane", centralized_or_distributed="Logically centralised knowledge plane",
    single_or_multidomain="Single domain", closed_loop="Yes (conceptually - the knowledge plane closes the loop)",
    sla_support="NR", network_slicing="No", cloud_native="No", kubernetes="No", oran="No",
    optimization="ML + reasoning", ml="Yes (conceptual)", agent="No", llm="No",
    evaluation_platform="N/A (position paper)", network_scale="N/A", baselines="N/A", metrics="N/A",
    main_results="N/A (position paper)",
    limitations="Vision paper: no implementation or measurement; does not solve how the knowledge plane makes safe, verifiable decisions.",
    research_gap="The KDN vision is the conceptual ancestor of today's LLM/agent orchestrators; the open problem of verifiable autonomous decision-making is exactly what remains unsolved.",
    source_url="https://doi.org/10.1145/3138808.3138810", evidence="BIB", is_foundational=True,
)

C["O33"] = dict(
    in_orch=True, network_generation="6G (SAGIN)", domain="Multi-domain (ground/air/space)",
    orchestrator_type="F - LLM-based orchestrator (LLM planner + continual RL executors)",
    architecture="ARC (Autonomous Reinforcement Coordination): a two-tier orchestrator. Tier 1 is a RAG-based LLM (LLaMA 3.1-8B, not fine-tuned) that sequences users and tracks the active objective; Tier 2 is a set of specialised Double Dueling Deep Q-Learning agents (one per action type, Mixture-of-Experts style) that execute allocations. Static and Dynamic Knowledge Bases hold service specifications, objective profiles, action profiles, state history and [input, CoT, output] reasoning exemplars.",
    control_plane="Not mapped to a standard management plane (no ETSI ZSM/ONAP/OSM/O-RAN SMO named); positioned as an infrastructure-level orchestration layer",
    managed_resources="Compute (node MIPS), storage capacity, link bandwidth and latency, radio channel assignment, transmit power, routing paths",
    input="Strategist textual commands; user service requests; semantic QoE feedback; monitored per-(user,service,resource) state; service specifications (functional-block DAGs); action profiles; state history",
    output="An ordered user sequence, and per user: hosting node per functional block, compute and storage allocation, routing path (next hop, channel, transmit power)",
    interfaces="Internal LLM prompts only; no A1/E2/O1/O2/REST/NETCONF/YANG/TMF/CAMARA/Kubernetes API named",
    centralized_or_distributed="Hierarchical: one central RAG + LLM sequencer, distributed specialised RL agents",
    single_or_multidomain="Multi-domain (terrestrial + airborne + space layers)",
    closed_loop="Yes - per time slot: monitor -> LLM QoE evaluation -> allocate -> apply -> reward -> update exemplars and RL weights",
    sla_support="Semantic-space QoE threshold rather than a formal SLA object (reward 0 and resource reclamation when the threshold is not met)",
    network_slicing="No (service abstraction = directed graph of functional blocks)",
    cloud_native="NR", kubernetes="NR", oran="No",
    optimization="Hybrid: LLM reasoning (user sequencing, objective tracking) + D3QL RL agents (per-action allocation) + mathematical solvers offline to bootstrap exemplars",
    ml="Yes", agent="Yes (LLM sequencer + RL executors)", llm="Yes - LLaMA 3.1-8B, no fine-tuning, RAG + CoT few-shot with contrastive exemplars",
    evaluation_platform="Bespoke numerical simulation (no named simulator/testbed)",
    network_scale="10 nodes (half non-terrestrial), 10 users, one functional block per service (2-5 MIPS), node capacity 10-100 MIPS, link latency 1-10 ms, link capacity 10-100 Mbps; one deliberate topology change at iteration 30,000",
    baselines="Optimal (solver), RU-ARC (reward-unaware), NR-ARC (no RL agents - LLM does low-level allocation)",
    metrics="Normalised allocation cost; reward = average resource cost / allocated cost; number of supported users",
    main_results="Figure-only; the text claims ARC achieves near-optimal cost, recovers after the iteration-30,000 transition where RU-ARC fails, and that NR-ARC fluctuates more because of LLM instability. No numerical values are stated.",
    limitations="Single small-scale simulation (10 nodes/10 users); two figures with no numbers; no comparison to any external published orchestrator or standard DRL/optimisation baseline; exemplar bootstrapping requires an exact solver; no SLA object, no slicing, no standard management-plane mapping, no testbed.",
    research_gap="The clearest published template for LLM-planner + RL-executor orchestration, and it exposes exactly the open problems: quantitative benchmarking against external baselines, grounding in a standard management plane, hallucination verification of planner decisions, and SLA-level scoring.",
    source_url="https://doi.org/10.1109/MCOM.001.2400526", evidence="FULL",
    abstract_note="Full text read as the IEEE-accepted manuscript arXiv:2502.16198v1.",
)

C["O38"] = dict(
    in_orch=True, network_generation="5G", domain="Transport + core compute (single infrastructure)",
    orchestrator_type="B - optimisation/learning algorithm usable by an orchestrator",
    architecture="Distributed multi-agent A2C architecture: link controllers and node controllers, each holding actor-critic pairs per slice class and resource type (bandwidth, compute, memory); a central training manager collects observations offline and broadcasts updated policies.",
    control_plane="Not implemented against a standard management plane; conceptually a slice broker above the infrastructure",
    managed_resources="Link bandwidth, node computational capacity, node memory capacity",
    input="Per-flow demand vectors r_phi = [throughput, compute, memory, delay] with Markov-modulated demand (10 states); flow endpoints; performance functions; local observations",
    output="Per-flow per-timeslot allocated resource vector (bandwidth per link, compute and memory per node)",
    interfaces="NR (abstract 'central database' for observations)",
    centralized_or_distributed="Distributed inference with centralised offline training",
    single_or_multidomain="Single domain with hierarchical slices/multiple tenants",
    closed_loop="Yes - per-timeslot reward, policies refined continuously (online training supported)",
    sla_support="Yes - each flow has a performance function F in [0,1] where 1 means the SLA is fully met; eMBB uses a smooth concave function, URLLC a step function",
    network_slicing="Yes - eMBB and URLLC slice classes over one infrastructure, hierarchical slicing across tenants",
    cloud_native="NR", kubernetes="NR", oran="NR",
    optimization="Advantage Actor-Critic (A2C) DRL; transfer learning across topologies; genetic algorithms discussed but rejected as an online engine",
    ml="Yes (DRL)", agent="Yes (cooperative multi-agent DRL)", llm="No",
    evaluation_platform="Authors' own custom simulation; three topologies (Dumbbell, Triangle, Pyramid) plus a harder Pyramid+ variant; fluid traffic model with discretised timeslots",
    network_scale="2-6 flows in the main scenarios (scalability studied up to 9); link rate 50 Gbps; core node 60 Gbps compute / 60 Gb memory; access node 20 Gbps / 20 Gb; link propagation delay 0.1 ms; eMBB demand 0.30-42.5 Gbps with 20 ms delay; URLLC demand 2.08-10 Gbps with 1 ms delay; 2 slice classes",
    baselines="Static allocation; empirical heuristic; cross-topology transfer variants (DRL-D, DRL-T, DRL-DP, DRL-TP)",
    metrics="Expected system utility E[Omega]; per-resource utility E[Omega_rho] for throughput/compute/memory/delay; probability that Omega exceeds a threshold",
    main_results="DRL-D and DRL-T keep Omega > 0.45 in almost 50% of test episodes, a 10% gain over the empirical algorithm (Dumbbell). With the empirical algorithm 50% of episodes exceed Omega > 0.5, raised to 0.65-0.7 by the DRL strategies. DRL trained on one topology generalises to the Pyramid topology without retraining. Transfer learning raises E[Omega_c] by more than 5%. In the harder Pyramid+ scenario the empirical heuristic slightly beats DRL on throughput and delay.",
    limitations="Static routes assumed (routing not optimised); simulation only with 2-6 flows and hand-set parameters; no admission control (listed as future work); centralised observation database for training; results read from the pre-review 2021 preprint, so the published ToN version may differ; in the hardest scenario the simple heuristic wins.",
    research_gap="Distributed DRL beats static/empirical allocation and transfers across topologies, but stops at allocation over fixed routes in one domain. The gap is joint routing+placement+allocation, admission control, decentralised training, hard SLA enforcement, and cross-domain (RAN/transport/core) closed loops.",
    source_url="https://doi.org/10.1109/TNET.2022.3187310", evidence="FULL",
    abstract_note="Full text read as author preprint arXiv:2105.07946v1; published version paywalled.",
)

C["O41"] = dict(
    in_orch=True, network_generation="5G/6G", domain="O-RAN (RAN orchestration)",
    orchestrator_type="F - LLM-based orchestrator (hierarchical MCP agents inside O-RAN SMO/RIC)",
    architecture="ORION: LLM-assisted intent orchestration for O-RAN. An MCP-based SMO layer performs semantic translation of natural-language intents into slice/QoS policies; a non-RT RIC rApp and a near-RT RIC xApp enforce them via A1 and E2. Intents are grounded in the CAMARA NetworkSliceBooking schema; validation/composition flows span SMO app, rApp and xApp.",
    control_plane="O-RAN SMO + non-RT RIC + near-RT RIC (A1 and E2 enforcement)",
    managed_resources="RAN slice resources and QoS parameters",
    input="Natural-language intents; CAMARA slice-booking schema; KPI telemetry",
    output="A1 policies and E2-level enforcement actions for slices",
    interfaces="A1, E2, O1, MCP tool interface, CAMARA NetworkSliceBooking",
    centralized_or_distributed="Hierarchical (SMO above non-RT RIC above near-RT RIC)",
    single_or_multidomain="Single RAN domain",
    closed_loop="Yes - the paper positions enforcement plus KPI-driven corrective actions as the closed loop, though the measured evaluation focuses on provisioning and policy generation",
    sla_support="Yes - SLA/SLO preservation is the stated motivation and intents carry KPI targets",
    network_slicing="Yes (eMBB/URLLC/mMTC slice intents)", cloud_native="Yes", kubernetes="Yes", oran="Yes",
    optimization="LLM-based translation with schema validation; no numerical optimiser",
    ml="LLM", agent="Yes (hierarchical agents over MCP tools)", llm="Yes - six commercial models evaluated including GPT-5, Gemini 3 Pro, Claude Opus",
    evaluation_platform="Prototype combining MCP services with O-RAN-compliant control functions; resource overhead and end-to-end latency measured",
    network_scale="NR", baselines="Comparison across six LLMs rather than against a non-LLM orchestrator",
    metrics="Policy generation success rate; translation fidelity against a 100-intent dataset; tool-use reliability; resource overhead; end-to-end latency; cost-performance trade-off",
    main_results="100% policy generation success rate for high-capacity models; the paper reports significant reasoning-efficiency trade-offs and a published dataset of 100 natural-language intents mapped to eMBB/URLLC/mMTC slice types and QoS parameters.",
    limitations="Preprint (arXiv:2603.03667) with no peer-reviewed version located; evaluation is provisioning/policy-generation centric rather than a measured SLA outcome under load; single RAN domain; no comparison to a classical optimisation baseline.",
    research_gap="The closest published attempt to place an LLM agent inside a standard O-RAN management hierarchy. What is missing is exactly what a PhD could add: measuring whether the enforced policies actually deliver SLA-level outcomes, and comparing against classical/DRL optimisation on the same intents.",
    source_url="https://arxiv.org/abs/2603.03667", evidence="FULL", arxiv="2603.03667", peer_reviewed=False,
)

for k, v in C.items():
    if k in by:
        by[k].update(v)

json.dump(recs, open(os.path.join(DATA, "master_stage4.json"), "w"), indent=1)
print("stage4: characterised", len(C), "orchestration papers; total", len(recs))
