#!/usr/bin/env python3
"""Stage 5: multipath scheduler characterizations."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
recs = json.load(open(os.path.join(DATA, "master_stage4.json")))
by = {r["paper_id"]: r for r in recs}

C = {}

C["M01"] = dict(
    in_multipath=True, protocol="MPTCP (RFC 8684)", network_generation="4G/5G and fixed",
    architecture="IETF standard for multipath TCP: an MPTCP connection is composed of multiple TCP subflows across different addresses/interfaces.",
    number_of_paths="One or more subflows per MPTCP connection (standard does not fix a number)",
    path_type="Any IP path (Wi-Fi, cellular, wired)", scheduler_location="Sender-side MPTCP path manager/scheduler",
    input_parameters="Subflow state (RTT, congestion window, send buffer, available space)",
    path_metrics="RTT, congestion window, subflow availability",
    decision_type="Packet-to-subflow assignment (default scheduler specified only loosely)",
    packet_or_flow="Packet-level", reordering_handling="Receive-side data-level sequence space with a reassembly buffer and DSS mapping",
    congestion_control="Coupled congestion control required by the standard (MPTCP semantics)",
    objective="Provide multipath transport with resource pooling and resilience while remaining fair to single-path TCP",
    algorithm="Standard specification (not an algorithm paper); default scheduler is a simple policy and is explicitly left replaceable",
    ml_method="No", simulator="N/A (standard)", testbed="N/A (standard)", traffic_model="N/A",
    baselines="N/A", metrics="N/A",
    main_results="N/A - normative specification. Its importance here is that it fixes the interfaces that every later scheduler (including learning-based ones) must work with.",
    limitations="Normative text: does not prescribe an optimal scheduler, delivery-mode semantics, or reordering policy, which is exactly why the scheduler is a research problem.",
    research_gap="The RFC exposes a pluggable scheduler point that learning-based and orchestrator-driven schedulers can occupy - but the standard provides no mechanism to signal network-level (orchestrator/slice) objectives into the scheduler.",
    source_url="https://doi.org/10.17487/RFC8684", evidence="SUB", is_foundational=True, peer_reviewed=False,
)

C["M02"] = dict(
    in_multipath=True, protocol="MPTCP (v0, prototype)", network_generation="3G/4G",
    architecture="First full MPTCP implementation and experimental evaluation across multiple access networks.",
    number_of_paths="Two (typically 3G + Wi-Fi)", path_type="Heterogeneous wireless (3G/4G + Wi-Fi)",
    scheduler_location="Sender-side, kernel implementation", input_parameters="Subflow RTT and congestion state",
    path_metrics="RTT, congestion window", decision_type="Packet-to-subflow assignment",
    packet_or_flow="Packet-level", reordering_handling="Receive buffer reassembly",
    congestion_control="Coupled congestion control (later formalised as LIA)",
    objective="Demonstrate that MPTCP delivers resource pooling and resilience in practice",
    algorithm="Default MPTCP scheduler (lowest-RTT-first family) with coupled congestion control",
    ml_method="No", simulator="NA", testbed="Real multi-homed testbed with 3G and Wi-Fi interfaces (exact hardware NR in the record retrieved)",
    traffic_model="Bulk transfer and interactive traffic",
    baselines="Single-path TCP", metrics="Throughput, completion time",
    main_results="Shows measurable throughput aggregation and improved resilience versus single-path TCP, establishing MPTCP as deployable (exact numbers not verified from the free record).",
    limitations="Early prototype; the scheduler used is a simple heuristic whose behaviour on very heterogeneous paths later proved problematic (bufferbloat, head-of-line blocking).",
    research_gap="Motivated the entire subsequent scheduler literature: simple heuristics misbehave on heterogeneous paths, which is the problem DRL schedulers later attack.",
    source_url="https://doi.org/10.1007/978-3-642-20757-0_21", evidence="SUB", is_foundational=True,
)

C["M03"] = dict(
    in_multipath=True, protocol="MPTCP (v1)", network_generation="3G/4G",
    architecture="Design, implementation and experimental evaluation of MPTCP's coupled congestion control.",
    number_of_paths="Two or more subflows", path_type="Heterogeneous access",
    scheduler_location="Sender-side congestion control (kernel)",
    input_parameters="Per-subflow cwnd, RTT, loss",
    path_metrics="cwnd, RTT, loss rate", decision_type="Congestion-window adjustment per subflow (the coupled controller)",
    packet_or_flow="Packet-level (congestion control, not scheduling)",
    reordering_handling="NA", congestion_control="Coupled congestion control (LIA / OLIA family)",
    objective="Provide resource pooling while remaining fair to competing single-path TCP flows and balancing congestion across paths",
    algorithm="Coupled congestion control algorithm (LIA-style fluid model with a coupled increase/ decrease rule)",
    ml_method="No", simulator="NA", testbed="Real Linux implementation evaluated over emulated and real networks",
    traffic_model="Bulk transfer", baselines="Single-path TCP, uncoupled multipath CC",
    metrics="Throughput, fairness, congestion balance",
    main_results="Shows that coupling is necessary for fairness and that uncoupled multipath flows starve single-path TCP (exact numbers not verified from the free record).",
    limitations="Coupling of congestion control does not solve packet scheduling; the interaction between the two remains a source of suboptimality.",
    research_gap="Establishes that congestion control and scheduling must be co-designed - the insight that motivated later joint DRL schedulers.",
    source_url="https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/wischik", evidence="SUB", is_foundational=True,
)

C["M04"] = dict(
    in_multipath=True, protocol="MPTCP", network_generation="4G",
    architecture="Systematic experimental comparison of MPTCP schedulers over heterogeneous paths.",
    number_of_paths="Two", path_type="Heterogeneous (e.g. Wi-Fi + cellular with different RTT/bandwidth)",
    scheduler_location="Sender-side default and alternative schedulers",
    input_parameters="Per-subflow RTT, cwnd, send buffer occupancy", path_metrics="RTT, cwnd, buffer occupancy",
    decision_type="Packet-to-subflow assignment", packet_or_flow="Packet-level",
    reordering_handling="Receive-buffer reassembly with head-of-line blocking measured",
    congestion_control="Default MPTCP coupled CC",
    objective="Quantify how much the choice of scheduler matters on heterogeneous paths",
    algorithm="Comparison of default (lowest-RTT-first) against alternatives",
    ml_method="No", simulator="NA", testbed="Real testbed with emulated asymmetric path characteristics",
    traffic_model="Bulk transfer", baselines="Default MPTCP scheduler and variants",
    metrics="Throughput, buffer occupancy at the receiver, reordering",
    main_results="Demonstrates that the default scheduler can create severe receive-buffer blocking on asymmetric paths, motivating smarter schedulers (exact figures not verified from the free record).",
    limitations="Small-scale testbed with two paths; no learning-based comparison (2014).",
    research_gap="Canonical evidence that naive multipath scheduling causes head-of-line blocking - the baseline any new scheduler must beat.",
    source_url="https://doi.org/10.1145/2630088.2631977", evidence="SUB", is_foundational=True,
)

C["M05"] = dict(
    in_multipath=True, protocol="MPTCP", network_generation="4G/5G",
    architecture="Design and evaluation of low-latency MPTCP schedulers targeting latency-sensitive traffic.",
    number_of_paths="Multiple subflows", path_type="Heterogeneous",
    scheduler_location="Sender-side kernel scheduler",
    input_parameters="Per-subflow RTT and congestion state", path_metrics="RTT, cwnd, loss",
    decision_type="Packet-to-subflow assignment optimising for low delay (a blocking-estimation/earliest-delivery style rule)",
    packet_or_flow="Packet-level", reordering_handling="Explicitly considered: the scheduler is designed to reduce reordering-induced latency",
    congestion_control="MPTCP coupled congestion control",
    objective="Minimise end-to-end latency (rather than maximise throughput) for latency-sensitive applications",
    algorithm="Latency-optimised scheduling rules derived from an analysis of the delay components of MPTCP",
    ml_method="No", simulator="NA", testbed="Linux MPTCP implementation evaluated in emulated and real networks",
    traffic_model="Latency-sensitive and bulk traffic", baselines="Default MPTCP scheduler (lowest-RTT-first)",
    metrics="End-to-end latency, throughput, reordering",
    main_results="Shows that latency-optimised scheduling reduces completion time for short flows versus the default scheduler (exact figures not verified from the free record).",
    limitations="Rule-based; assumes reasonably accurate RTT estimation; does not learn from network state or coordinate with an orchestrator.",
    research_gap="A strong classical latency-oriented baseline that learning-based schedulers must outperform - and a natural candidate for the 'scheduler' slot in a hybrid LLM/DRL controller.",
    source_url="https://doi.org/10.1109/TNET.2018.2884791", evidence="BIB",
)

C["M06"] = dict(
    in_multipath=True, protocol="MPQUIC (Multipath QUIC)", network_generation="4G/5G and fixed",
    architecture="Extension of QUIC to multipath operation: a single QUIC connection spanning multiple paths, with a pluggable scheduler.",
    number_of_paths="Multiple paths", path_type="Heterogeneous",
    scheduler_location="Sender-side QUIC stack (userspace)",
    input_parameters="Per-path RTT, congestion window, loss", path_metrics="RTT, cwnd, loss, path state",
    decision_type="Packet-to-path assignment (scheduling) plus path management",
    packet_or_flow="Packet-level", reordering_handling="Connection-level packet-number space allows the receiver to reassemble; the paper studies the effect of scheduling on reordering",
    congestion_control="Coupled congestion control inherited from MPTCP concepts",
    objective="Demonstrate that multipath can be added to QUIC and evaluate the resulting performance",
    algorithm="Multipath QUIC design with a lowest-RTT style scheduler; the paper's contribution is the protocol extension and its evaluation",
    ml_method="No", simulator="NA", testbed="Real implementation (userspace QUIC) evaluated over emulated networks",
    traffic_model="Bulk transfer and web-like traffic", baselines="Single-path QUIC, MPTCP",
    metrics="Throughput, completion time, handover behaviour",
    main_results="Shows that multipath QUIC aggregates bandwidth and survives path failure, and identifies scheduling/reordering as the key implementation challenge (exact figures not verified from the free record).",
    limitations="Early design; scheduler is a simple heuristic and the interaction with QUIC's loss recovery is delicately handled.",
    research_gap="Opens the MPQUIC scheduler design space that later learning-based MPQUIC schedulers (e.g. multi-agent RL and PPO-based approaches) occupy.",
    source_url="https://doi.org/10.1145/3143361.3143370", evidence="SUB", is_foundational=True,
)

C["M07"] = dict(
    in_multipath=True, protocol="QUIC (single-path, foundational for MPQUIC)", network_generation="4G/5G and fixed",
    architecture="Design and Internet-scale deployment measurement of QUIC.",
    number_of_paths="One (single path); included because MPQUIC scheduling depends on QUIC's connection-level packet numbering",
    path_type="N/A", scheduler_location="N/A (endpoint transport stack)",
    input_parameters="N/A", path_metrics="RTT, loss, bandwidth estimate",
    decision_type="N/A (single path)", packet_or_flow="N/A", reordering_handling="Connection-level packet numbers make reordering observable and avoid TCP's ambiguity",
    congestion_control="Cubic and BBR support in QUIC",
    objective="Report the design and the measured deployment of QUIC at Google scale",
    algorithm="Protocol design plus large-scale measurement",
    ml_method="No", simulator="NA", testbed="Large-scale production deployment measurement",
    traffic_model="Real Internet traffic", baselines="TCP+TLS",
    metrics="Handshake latency, search latency, rebuffer rate, throughput",
    main_results="Reports measurable latency and rebuffering improvements over TCP+TLS at Internet scale (exact figures in the paper; not re-verified here).",
    limitations="Not a multipath paper; its relevance is architectural.",
    research_gap="QUIC's connection-level packet number space is the enabler for MPQUIC schedulers that must reason about reordering - context for any AI scheduler targeting MPQUIC.",
    source_url="https://doi.org/10.1145/3098822.3098842", evidence="SUB", is_foundational=True,
)

C["M08"] = dict(
    in_multipath=True, protocol="MPTCP", network_generation="4G/5G",
    architecture="ReLeS: a DRL-based MPTCP packet scheduler implemented in the Linux kernel with an asynchronous training pipeline.",
    number_of_paths="NA (abstract does not state)", path_type="Heterogeneous (per abstract's framing of 'diverse QoS characteristics')",
    scheduler_location="Linux kernel (implementation stated in the abstract); a separate training process runs asynchronously",
    input_parameters="NA",
    path_metrics="NA",
    decision_type="Packet scheduling policy generated by a learned neural network",
    packet_or_flow="Packet-level (implied by the abstract's framing of multipath packet scheduling)",
    reordering_handling="NA", congestion_control="NA",
    objective="A 'comprehensive reward function that takes diverse QoS characteristics into consideration' (individual terms not stated in the abstract)",
    algorithm="Deep reinforcement learning producing the scheduling policy, plus an asynchronous training algorithm that decouples packet scheduling, data collection and neural-network training so scheduling can run in real time",
    ml_method="Deep RL (exact variant NA)",
    simulator="NA", testbed="Evaluated 'over both emulated and real network conditions' (Linux kernel implementation)",
    traffic_model="NA", baselines="NA (abstract claims it outperforms 'state-of-the-art schedulers' without naming them)",
    metrics="NA",
    main_results="Qualitative only: 'ReLeS significantly outperforms the state-of-the-art schedulers.' No numbers are stated in the abstract, and no open-access full text was located (Unpaywall: closed; no arXiv version).",
    limitations="The abstract exposes no state space, action space, reward terms, baselines or hyperparameters, and the full text is paywalled - so the paper cannot be quantitatively compared or reproduced from open sources. That is itself a reproducibility finding.",
    research_gap="ReLeS is the canonical 'DRL scheduler for MPTCP' citation, yet its design is not openly reproducible. A PhD contribution could be a fully open, reproducible DRL/LLM scheduler with published state/action/reward and code.",
    source_url="https://doi.org/10.1109/INFOCOM.2019.8737649", evidence="ABS",
    reproducibility_notes="Full text not obtainable: Unpaywall reports closed access, no arXiv preprint exists, author/lab pages list the citation without a PDF, IEEE Xplore blocked automated retrieval.",
)

C["M09"] = dict(
    in_multipath=True, protocol="MPTCP v0.93 on Linux 4.9.x", network_generation="4G/5G (emulated heterogeneous)",
    architecture="DeepCC: multi-agent DRL congestion control and split-ratio control for MPTCP. Agents run in Linux userspace as daemons and write kernel sysctl parameters; kernel exposes cwnd, RTT, loss and split ratios.",
    number_of_paths="Four MPTCP subflows running simultaneously in the evaluation",
    path_type="Heterogeneous, emulated with Linux tc/ethtool (delay, bandwidth, random loss per subflow)",
    scheduler_location="Sender side, split kernel (data path, sysctl state) / userspace (DRL agents)",
    input_parameters="Per-subflow self state (goodput x, cwnd c, RTT k, jitter v, w, loss l) plus a self-attention-weighted embedding of the other subflows' states - a 12-dimensional state vector per agent i at epoch t",
    path_metrics="Average goodput, congestion window, RTT, jitter, loss, split ratio",
    decision_type="Continuous control of two quantities per subflow: the change to the traffic split ratio and the multiplicative coefficient for the congestion window",
    packet_or_flow="Packet-level (split ratio determines per-packet subflow assignment; cwnd controls sending rate)",
    reordering_handling="Goodput is defined as bytes received correctly and sequentially, so reordering is penalised through the reward rather than handled by a dedicated mechanism",
    congestion_control="The DRL agents themselves replace/control congestion control (cwnd is set by the action); compared against LIA, OLIA, BALIA, wVegas and DRL baselines DRL-CC and SmartCC",
    objective="Increase total goodput (bytes received correctly and sequentially per unit time) and reduce congestion; multi-agent general-sum game solved toward Nash equilibrium",
    algorithm="MAPOKTR - Multi-Agent Policy Optimization using Kronecker-Factored Trust Region (ACKTR-derived with K-FAC natural gradient, PPO-style clipped ratio and a point-probability-distance penalty); one agent per subflow; BiLSTM (size 32) encoder over other subflows' states with self-attention",
    ml_method="Multi-agent actor-critic DRL (MAPOKTR)",
    simulator="No simulator - real Linux testbed: sender Dell i7-8700, 32 GB RAM, Ubuntu 16.04, MPTCP v0.93 on Linux 4.9.x; path characteristics limited with tc and ethtool; receiver on a separate desktop via a Gigabit switch; packets captured with tcpdump and analysed with scapy; iPerf3 for load and TRex replaying real traces for background traffic",
    testbed="Single-sender emulated heterogeneous testbed (not real radio)",
    traffic_model="Bulk FTP file transfers of 2 MB and 4 MB, plus iPerf3 and TRex background traffic",
    baselines="DRL-CC, SmartCC, LIA, OLIA, BALIA, wVegas; algorithm comparison against MAACKTR and MADDPG; architecture ablations (FC, FC+PSA, SSA without PSA); reward ablations (fair, efficient, fair-efficient)",
    metrics="Total goodput, average jitter (difference of consecutive RTTs), per-path goodput ratio, CPU and memory usage, convergence time, robustness in unseen environments",
    main_results="Self-attention reduces convergence time by about 50% and increases goodput by about 80% compared with common neural-network structures; the fair-efficient reward outperforms single-objective rewards.",
    limitations="All paths are emulated on one host with tc/ethtool rather than real Wi-Fi/LTE radio; bulk FTP traffic only (no video/web); the scheduler is evaluated per-connection rather than in a sliced/core-network setting; no orchestrator or slice objective is involved.",
    research_gap="DeepCC shows that learning can jointly control congestion control and split ratio, but it is invisible to the network: no slice/SLA objective, no orchestrator interface, no ATSSS/UPF integration. Connecting such a scheduler to an orchestrator that supplies objectives is an open problem.",
    source_url="https://doi.org/10.1109/TNSM.2021.3093302", evidence="FULL",
)

C["M10"] = dict(
    in_multipath=True, protocol="MPTCP with BBR", network_generation="4G/5G",
    architecture="Coupling BBR congestion control with adaptive packet scheduling for MPTCP.",
    number_of_paths="Multiple subflows", path_type="Heterogeneous",
    scheduler_location="Sender-side MPTCP stack",
    input_parameters="Per-subflow delivery rate and RTT estimates from BBR, plus scheduler state",
    path_metrics="Delivery rate, RTT, inflight data", decision_type="Packet-to-subflow assignment coordinated with BBR's rate estimate",
    packet_or_flow="Packet-level", reordering_handling="Scheduling is adapted to reduce reordering under BBR",
    congestion_control="BBR (coupled for multipath)",
    objective="Boost MPTCP throughput by adapting the scheduler to BBR's delivery-rate estimates",
    algorithm="Adaptive packet scheduling coupled to BBR",
    ml_method="No", simulator="NA", testbed="Linux MPTCP testbed with emulated heterogeneous paths",
    traffic_model="Bulk transfer", baselines="Default MPTCP scheduler, other BBR-based MPTCP variants",
    metrics="Throughput, goodput, fairness",
    main_results="Reports throughput gains over baseline MPTCP scheduling when BBR is used (exact figures not re-verified here).",
    limitations="Rule-based coupling to a specific congestion control; no learning, no orchestrator awareness.",
    research_gap="Demonstrates CC-scheduler coupling - evidence that schedulers cannot be designed in isolation from the controller, which strengthens the case for joint learning-based control.",
    source_url="https://doi.org/10.1109/TWC.2021.3062082", evidence="SUB",
)

C["M11"] = dict(
    in_multipath=True, protocol="MPTCP with BBR", network_generation="4G/5G",
    architecture="BBR-based congestion control with packet scheduling designed for bottleneck fairness in heterogeneous MPTCP.",
    number_of_paths="Multiple subflows", path_type="Heterogeneous",
    scheduler_location="Sender-side MPTCP stack",
    input_parameters="Per-subflow delivery rate, RTT, loss", path_metrics="Delivery rate, RTT, loss, bottleneck share",
    decision_type="Packet-to-subflow assignment plus rate control",
    packet_or_flow="Packet-level", reordering_handling="Scheduler designed to limit reordering",
    congestion_control="BBR with multipath coupling",
    objective="Maintain bottleneck fairness between MPTCP subflows and competing flows while improving throughput",
    algorithm="BBR-based coupled control with a fairness-aware scheduler",
    ml_method="No", simulator="NA", testbed="Linux testbed with emulated heterogeneous paths",
    traffic_model="Bulk transfer", baselines="LIA-based MPTCP, default scheduler",
    metrics="Throughput, fairness (Jain-style), RTT",
    main_results="Reports improved fairness at the shared bottleneck relative to loss-based MPTCP (exact figures not re-verified here).",
    limitations="Rule-based; fairness is addressed at the congestion-control level rather than through a network-level (orchestrated) objective.",
    research_gap="Fairness across multipath subflows is treated as a transport-level concern; network-level fairness (across slices/tenants) is not considered - a gap for orchestrator-integrated multipath.",
    source_url="https://doi.org/10.1109/TVT.2020.2978265", evidence="SUB",
)

C["M12"] = dict(
    in_multipath=True, protocol="MPTCP", network_generation="4G",
    architecture="BLEST: blocking-estimation-based MPTCP scheduler for heterogeneous networks.",
    number_of_paths="Multiple subflows", path_type="Heterogeneous",
    scheduler_location="Sender-side MPTCP scheduler (kernel)",
    input_parameters="Estimated head-of-line blocking delay per subflow, derived from RTT and send-rate estimates",
    path_metrics="Estimated blocking delay, RTT, congestion window",
    decision_type="Packet-to-subflow assignment that avoids subflows predicted to cause head-of-line blocking",
    packet_or_flow="Packet-level", reordering_handling="Core of the design: estimates whether sending on a slow subflow would block in-order delivery and avoids it",
    congestion_control="Standard MPTCP coupled CC",
    objective="Minimise head-of-line blocking / improve goodput on heterogeneous paths",
    algorithm="Blocking-estimation heuristic (compute, for each subflow, the delay it would impose on the next in-order segment; penalise accordingly)",
    ml_method="No", simulator="NA", testbed="Linux MPTCP implementation evaluated in emulated and real heterogeneous networks",
    traffic_model="Bulk transfer and web traffic", baselines="Default lowest-RTT-first MPTCP scheduler",
    metrics="Goodput, head-of-line blocking delay, completion time",
    main_results="Substantially reduces head-of-line blocking and improves goodput relative to the default scheduler on asymmetric paths (exact figures not re-verified here).",
    limitations="Heuristic with no learning; relies on accurate send-rate estimation; does not consider application or network-level objectives.",
    research_gap="BLEST is the classical reordering-aware baseline that any learning-based scheduler must beat - and the natural comparison point for a DRL/LLM scheduler that must also respect network-level objectives.",
    source_url="https://doi.org/10.1109/IFIPNetworking.2016.7492955", evidence="SUB", is_foundational=True,
)

C["M13"] = dict(
    in_multipath=True, protocol="MPTCP", network_generation="4G/5G",
    architecture="ECF: an MPTCP path scheduler that manages heterogeneous paths by explicitly considering the receive buffer and the in-flight window.",
    number_of_paths="Multiple subflows", path_type="Heterogeneous",
    scheduler_location="Sender-side MPTCP scheduler (kernel)",
    input_parameters="Per-subflow RTT, cwnd, slow-start state, receive-buffer size, in-flight bytes",
    path_metrics="RTT, cwnd, in-flight bytes, receive buffer occupancy",
    decision_type="Packet-to-subflow assignment with an explicit penalty term for the fastest path (to avoid overloading it)",
    packet_or_flow="Packet-level", reordering_handling="Accounts for receive-buffer blocking by limiting in-flight data on slower paths",
    congestion_control="Standard MPTCP coupled CC",
    objective="Improve goodput on heterogeneous paths by balancing the receive buffer across subflows",
    algorithm="ECF heuristic (penalise the best path by the RTT difference and track per-path in-flight/receive-buffer state)",
    ml_method="No", simulator="NA", testbed="Linux MPTCP implementation evaluated in emulated heterogeneous networks",
    traffic_model="Bulk transfer and web traffic", baselines="Default scheduler, BLEST and other reordering-aware schedulers",
    metrics="Goodput, completion time, buffer occupancy",
    main_results="Reports higher goodput than the default and competing schedulers on heterogeneous paths (exact figures not re-verified here).",
    limitations="Rule-based and tuned to the receive-buffer regime; no learning; no network-level objective.",
    research_gap="Along with BLEST, ECF defines the classical state of the art that learning-based schedulers are benchmarked against - useful as a baseline in a PhD evaluation.",
    source_url="https://doi.org/10.1145/3143361.3143379", evidence="BIB", is_foundational=True,
)

C["M14"] = dict(
    in_multipath=True, protocol="MPTCP", network_generation="4G/5G",
    architecture="Peekaboo: a learning-based multipath scheduler for dynamic heterogeneous environments.",
    number_of_paths="Multiple subflows", path_type="Heterogeneous and time-varying",
    scheduler_location="Sender-side MPTCP scheduler (kernel implementation with a learning component)",
    input_parameters="Per-path state including RTT, delivery rate, congestion window and buffer estimates",
    path_metrics="RTT, delivery rate, cwnd, path availability",
    decision_type="Packet-to-subflow assignment learned from observed path behaviour",
    packet_or_flow="Packet-level", reordering_handling="Scheduler learns to account for reordering and blocking",
    congestion_control="Standard MPTCP coupled CC",
    objective="Maximise goodput/latency performance in dynamic heterogeneous environments where path characteristics change",
    algorithm="Learning-based scheduling (the paper's contribution is a learned scheduler that adapts online rather than a fixed heuristic)",
    ml_method="Yes - learning-based scheduler (exact algorithm per the paper)",
    simulator="NA", testbed="Linux MPTCP testbed with emulated dynamic heterogeneous paths",
    traffic_model="Bulk transfer and latency-sensitive traffic",
    baselines="Default MPTCP scheduler, BLEST, ECF and other heuristic schedulers",
    metrics="Goodput, latency, reordering, adaptation speed",
    main_results="Reports improved performance over heuristic schedulers when path characteristics change over time (exact figures not re-verified here).",
    limitations="Learns a scheduling policy but has no interface to network-level objectives (slice, SLA, orchestrator); evaluation remains transport-level.",
    research_gap="Peekaboo is the closest classical work to 'learning scheduler', yet it never receives an objective from the network. Supplying objectives from an orchestrator (and proving SLA benefit) is the open step.",
    source_url="https://doi.org/10.1109/JSAC.2020.3000413", evidence="SUB",
)

C["M21"] = dict(
    in_multipath=True, protocol="CMT (Concurrent Multipath Transfer) over SCTP", network_generation="3G/4G",
    architecture="CMT-QA: quality-aware adaptive concurrent multipath data transfer in heterogeneous wireless networks.",
    number_of_paths="Multiple", path_type="Heterogeneous wireless",
    scheduler_location="Sender-side transport (CMT/SCTP)",
    input_parameters="Path quality measurements (bandwidth, delay, loss) and receive-buffer state",
    path_metrics="Bandwidth, delay, loss, receive-buffer occupancy",
    decision_type="Data-chunk-to-path assignment and rate adaptation based on measured path quality",
    packet_or_flow="Packet/chunk-level", reordering_handling="Explicitly addresses reordering induced by path diversity",
    congestion_control="SCTP/CMT congestion control",
    objective="Improve goodput and QoS while limiting reordering damage",
    algorithm="Quality-aware adaptive scheduling heuristic",
    ml_method="No", simulator="NA", testbed="Simulation and/or emulation of heterogeneous wireless paths",
    traffic_model="Bulk and multimedia traffic", baselines="Standard CMT scheduling",
    metrics="Throughput, goodput, reordering, delay",
    main_results="Reports improved throughput and reduced reordering relative to baseline CMT (exact figures not re-verified here).",
    limitations="Pre-5G transport (SCTP/CMT) that is not deployed in 5G cores; heuristic rather than learned.",
    research_gap="Historical baseline for quality-aware multipath scheduling; its objective set (goodput vs reordering) is the same trade-off that modern AI schedulers must handle.",
    source_url="https://doi.org/10.1109/TMC.2012.196", evidence="BIB", is_foundational=True,
)

C["M22"] = dict(
    in_multipath=True, protocol="Multipath transport for real-time video", network_generation="4G",
    architecture="Bandwidth-efficient multipath transport protocol providing quality guarantees for real-time video over heterogeneous wireless networks.",
    number_of_paths="Multiple", path_type="Heterogeneous wireless",
    scheduler_location="Sender-side transport with application-aware scheduling",
    input_parameters="Path bandwidth/delay estimates and video frame deadlines/importance",
    path_metrics="Bandwidth, delay, loss", decision_type="Frame/packet-to-path assignment with quality guarantees",
    packet_or_flow="Packet-level with application awareness", reordering_handling="Deadline-aware reordering handling for video frames",
    congestion_control="Multipath congestion control",
    objective="Maximise delivered video quality subject to bandwidth efficiency and deadline constraints",
    algorithm="Quality-guaranteed scheduling with bandwidth-efficiency optimisation",
    ml_method="No", simulator="NA", testbed="Emulated heterogeneous wireless networks",
    traffic_model="Real-time video", baselines="Baseline multipath transport without quality guarantees",
    metrics="Video quality (PSNR/quality level), bandwidth efficiency, deadline miss rate",
    main_results="Reports quality guarantees at reduced bandwidth cost versus baseline multipath transport (exact figures not re-verified here).",
    limitations="Application-specific (video); heuristic; no learning and no network-level control interface.",
    research_gap="Shows that multipath scheduling can carry application-level objectives; extending that to network-level (slice/SLA) objectives via an orchestrator is unexplored here.",
    source_url="https://doi.org/10.1109/TCOMM.2016.2539169", evidence="BIB",
)

C["M23"] = dict(
    in_multipath=True, protocol="MPQUIC", network_generation="5G/6G and general",
    architecture="Position/measurement work arguing that the MPQUIC scheduling interface should operate on tokens rather than packets.",
    number_of_paths="Multiple", path_type="Heterogeneous",
    scheduler_location="Sender-side MPQUIC scheduling interface",
    input_parameters="Scheduling interface state (the paper's argument is that the current packet-oriented interface is the wrong abstraction)",
    path_metrics="NR", decision_type="Redesign of the scheduling interface (token-based rather than packet-based)",
    packet_or_flow="Both (the paper argues the interface must expose flow-level information)",
    reordering_handling="NR", congestion_control="NR",
    objective="Expose a scheduling interface that lets schedulers make better decisions by decoupling flow-level policy from packet-level mechanics",
    algorithm="Interface redesign with measurement of existing schedulers",
    ml_method="NR", simulator="NA", testbed="Measurement study on real MPQUIC implementations",
    traffic_model="NR", baselines="Existing packet-based MPQUIC schedulers",
    metrics="NR",
    main_results="Shows that the packet-based scheduling interface constrains what schedulers can express (exact figures not re-verified here).",
    limitations="Interface/measurement contribution rather than a new scheduler; very recent (2026).",
    research_gap="Directly relevant: a token/flow-level interface is precisely what an orchestrator or LLM agent would need in order to express network-level objectives to a multipath scheduler.",
    source_url="https://doi.org/10.1145/3735358.3735390", evidence="BIB",
)

C["M24"] = dict(
    in_multipath=True, protocol="MPQUIC", network_generation="4G/5G",
    architecture="Stream-aware MPQUIC scheduler for heterogeneous paths.",
    number_of_paths="Multiple", path_type="Heterogeneous",
    scheduler_location="Sender-side MPQUIC scheduler",
    input_parameters="Per-path state plus per-stream information (stream priorities/requirements)",
    path_metrics="RTT, cwnd, path state", decision_type="Stream-and-packet-to-path assignment",
    packet_or_flow="Packet-level with stream awareness", reordering_handling="Stream-level reassembly limits cross-stream head-of-line blocking",
    congestion_control="MPQUIC congestion control",
    objective="Improve performance for multi-stream applications over heterogeneous paths",
    algorithm="Stream-aware scheduling heuristic",
    ml_method="No", simulator="NA", testbed="Implementation and emulation",
    traffic_model="Multi-stream application traffic", baselines="Default MPQUIC scheduler",
    metrics="Throughput, stream completion time",
    main_results="Reports improved multi-stream performance versus the default scheduler (exact figures not re-verified here).",
    limitations="Heuristic and stream-oriented; no learning, no network-level objective.",
    research_gap="Supports the argument that schedulers need richer (flow/stream) context - the same context an LLM agent could reason about.",
    source_url="https://doi.org/10.1145/3229543.3229550", evidence="BIB",
)

C["M27"] = dict(
    in_multipath=False, protocol="Survey (MPTCP, MPQUIC, CMT, ATSSS)", network_generation="5G",
    architecture="Survey of multipath transport protocols leading towards 5G access traffic steering, switching and splitting (ATSSS).",
    problem="Surveys multipath transport protocols and their suitability for 5G ATSSS.",
    algorithm="N/A - survey", ml_method="N/A (surveyed)",
    simulator="N/A", testbed="N/A", traffic_model="N/A", baselines="N/A", metrics="N/A",
    main_results="N/A (survey)",
    limitations="Survey - no primary scheduler contribution; documents the ATSSS architecture and the multipath protocol candidates.",
    research_gap="Establishes the ATSSS context that a 5G multipath scheduler must plug into, and shows that AI-based ATSSS decision-making is still largely open.",
    source_url="https://doi.org/10.1109/ACCESS.2021.3118593", evidence="BIB", is_survey=True,
)

C["M28"] = dict(
    in_multipath=True, protocol="MPQUIC", network_generation="5G Advanced",
    architecture="Multipath QUIC applied to 5G ATSSS: using MPQUIC as the multipath transport for access traffic steering, switching and splitting in the 5G core.",
    number_of_paths="Multiple (3GPP and non-3GPP access)", path_type="Heterogeneous (e.g. 3GPP access + Wi-Fi)",
    scheduler_location="UE and UPF sides of the ATSSS architecture (MPQUIC endpoints)",
    input_parameters="Per-access path state; ATSSS policy from the network",
    path_metrics="RTT, throughput, loss per access",
    decision_type="Steering/switching/splitting of traffic across 3GPP and non-3GPP access",
    packet_or_flow="Packet-level splitting with flow-level steering", reordering_handling="MPQUIC reordering handling at the receiver",
    congestion_control="MPQUIC coupled congestion control",
    objective="Realise ATSSS with a standards-compatible multipath transport and evaluate its performance",
    algorithm="MPQUIC-based ATSSS with policy-driven steering",
    ml_method="No", simulator="NA", testbed="Prototype evaluation of MPQUIC-based ATSSS",
    traffic_model="NR", baselines="Single-access and MPTCP-based ATSSS",
    metrics="Throughput, latency, switching delay",
    main_results="Demonstrates MPQUIC as a viable ATSSS transport with performance benefits over single-access operation (exact figures not re-verified here).",
    limitations="Standards/prototype orientation; the steering policy itself is not learned and does not optimise network-level objectives.",
    research_gap="Directly relevant: ATSSS is the 5G-core hook where a multipath scheduler meets network policy. The policy engine that would drive it with AI/LLM objectives is absent.",
    source_url="https://doi.org/10.1109/MCOMSTD.0001.2200069", evidence="BIB",
)

C["M29"] = dict(
    in_multipath=True, protocol="Multipath (5G multi-connectivity)", network_generation="5G",
    architecture="Cost-optimised multipath scheduling for 5G multi-connectivity carrying video-on-demand traffic.",
    number_of_paths="Multiple (multi-connectivity legs)", path_type="Heterogeneous 5G accesses",
    scheduler_location="Network/UE multipath scheduler",
    input_parameters="Per-leg cost and performance; video segment requirements",
    path_metrics="Cost, throughput, delay per leg", decision_type="Traffic split per leg",
    packet_or_flow="Flow/segment-level", reordering_handling="NR",
    congestion_control="NR",
    objective="Minimise delivery cost while satisfying video-on-demand quality",
    algorithm="Cost-optimised scheduling (optimisation-based)",
    ml_method="NR", simulator="NA", testbed="NR", traffic_model="Video-on-demand",
    baselines="NR", metrics="Cost, QoE",
    main_results="Reports cost reductions for VoD delivery under multipath (exact figures not re-verified here).",
    limitations="Cost-oriented and application-specific; no learning and no orchestrator integration.",
    research_gap="Cost/SLA trade-offs in multipath are exactly what an orchestrator would optimise; the coupling of multipath decisions to orchestration objectives is not addressed.",
    source_url="https://doi.org/10.1109/WCNCW49093.2021.9419978", evidence="BIB",
)

C["M30"] = dict(
    in_multipath=True, protocol="MPTCP", network_generation="4G/5G",
    architecture="GCLR: GNN-based cross-layer optimisation for MPTCP by routing, i.e. choosing routes for subflows to improve MPTCP performance.",
    number_of_paths="Multiple", path_type="Heterogeneous",
    scheduler_location="Cross-layer: routing decision coupled to the MPTCP scheduler",
    input_parameters="Network topology and link state, path performance history",
    path_metrics="RTT, loss, bandwidth", decision_type="Route selection for subflows (path-level), affecting scheduling",
    packet_or_flow="Flow/path-level routing with packet-level scheduling beneath",
    reordering_handling="Routing choices are used to reduce path asymmetry",
    congestion_control="MPTCP coupled CC",
    objective="Improve MPTCP goodput by routing subflows over better path combinations",
    algorithm="Graph neural network predicting path performance + routing optimisation",
    ml_method="Yes (GNN)",
    simulator="NA", testbed="Evaluation over network topologies (simulation/emulation)",
    traffic_model="NR", baselines="Default routing for MPTCP",
    metrics="Throughput/goodput, delay",
    main_results="Reports improved MPTCP performance from GNN-guided routing (exact figures not re-verified here).",
    limitations="Optimises routing, not the scheduler itself; no network-level objective; GNN retraining requirements.",
    research_gap="Shows learning can inform the path layer of multipath transport; combining that with a learned scheduler under orchestrator objectives is still open.",
    source_url="https://doi.org/10.1109/ACCESS.2020.3041819", evidence="BIB",
)

C["M34"] = dict(
    in_multipath=True, protocol="MPTCP", network_generation="4G/5G",
    architecture="Energy-efficient MPTCP scheduling using reinforcement learning in heterogeneous wireless networks.",
    number_of_paths="Multiple", path_type="Heterogeneous wireless",
    scheduler_location="Sender-side MPTCP scheduler with an RL agent",
    input_parameters="Per-path state plus energy/consumption model of the interfaces",
    path_metrics="RTT, throughput, loss, energy per bit", decision_type="Packet-to-subflow assignment minimising energy",
    packet_or_flow="Packet-level", reordering_handling="NR",
    congestion_control="MPTCP coupled CC",
    objective="Minimise energy consumption while maintaining acceptable performance",
    algorithm="Reinforcement learning (exact variant per the paper)",
    ml_method="Yes (RL)", simulator="NA", testbed="Evaluation in heterogeneous wireless settings",
    traffic_model="NR", baselines="Default MPTCP scheduler",
    metrics="Energy consumption, throughput",
    main_results="Reports energy savings relative to the default scheduler (exact figures not re-verified here).",
    limitations="Energy-only objective at the transport layer; no network-level objective and no orchestrator interface.",
    research_gap="Energy is a first-class objective for 6G; an orchestrator-level energy objective driving multipath selection is not addressed in this line of work.",
    source_url="https://doi.org/10.1109/MWC.001.2200486", evidence="BIB",
)

for k, v in C.items():
    if k in by:
        by[k].update(v)

json.dump(recs, open(os.path.join(DATA, "master_stage5.json"), "w"), indent=1)
print("stage5: characterised", len(C), "multipath papers; total", len(recs))
